### ISSUE TITLE
Transfer project?

### ISSUE THREAD

**Issue by stevenvachon** [stevenvachon/dotenv-prompt#1]
I'm interested in splitting out my dotenv work in [gres](https://npmjs.com/gres) to a separate package. This one hasn't been updated in a while and I could improve it quite a bit. If you aren't using it anymore, would you be interested in transferring its ownership to me?

**Comment by mitica** [comment]
Hi @stevenvachon I'll transfer it.

**Comment by stevenvachon** [comment]
Thanks!!

**Comment by stevenvachon** [comment]
In case you'd forgotten, please transfer the npm ownership as well.

**Comment by mitica** [comment]
Done!

**Comment by stevenvachon** [comment]
Thank you again
